conveyor/config: added new configuration for skipping backwards data checks
cockroachdb/replicator pull request #1052
Opened 2024-10-23 22:51 UTC by ryanluu12345

Previously, customers manually had to skip backwards data checks by updating source code. This change makes it so that they can now pass in a flag to control the behavior of if they want to perform that check or not.

Resolves: #1046
Release Note: new flag that controls if the backwards data check can be skipped

**TODO**
- [ ] Hide the flag from customers
- [ ] Add automated testing

**Local Testing**
When the `--ignoreBackwardsCheck` is specified (added debug logging for this then reverted)
```
time="Oct 23 15:48:17" level=debug httpRequest="&{0x140004bea00 45 200 3 3.617709ms   false false}"
ignore check:  true
```

2024-10-23 22:53 UTC, ryanluu12345 commented
Just wanted to give a note that I still need to add automated testing here. Any suggestions for what's simplest to test here are welcome :)

2024-10-23 22:59 UTC, ryanluu12345 commented on internal/conveyor/config.go
> +	// Marking this ignore check functionality as hidden in order to not
FYI @alicia-l2 hiding the flag here. Please let me know if you want me to update this comment. My understanding from our chat is we want to just give to customers as an as-needed basis since we don't want to encourage disabling this check.

2024-10-24 16:49 UTC, bobvawter reviewed
Refer to how `LimitLookahead` is already plumbed in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1052#-:-O9zQgXB4imUz21mNE9_:b-c8usvl)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @alicia-l2 and @Jeremyyang920)



<!-- Sent from Reviewable.io -->

2024-10-24 16:53 UTC, bobvawter requested changes
Specifically, there's already an options mechanism in the checkpoints package that allows it to be configured.

2024-10-24 17:30 UTC, ryanluu12345 reviewed
Great suggestion. This is a lot cleaner and configurable. I've made the relevant changes, tested locally, and verified the checkpoint tests still pass.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1052#-:-O9z_5op3eLUrMAPs6vI:b-wwpie2)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @alicia-l2 and @Jeremyyang920)



<!-- Sent from Reviewable.io -->

2024-10-24 18:01 UTC, bobvawter requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1052)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @alicia-l2, @Jeremyyang920, and @ryanluu12345)

___
*[`internal/staging/checkpoint/options.go` line 44 at r4](https://reviewable.io/reviews/cockroachdb/replicator/1052#-O9zflL416-YO20cVBW0:-O9zflL416-YO20cVBW1:b-1or8cx) ([raw file](https://github.com/cockroachdb/replicator/blob/4957f647e1290d2eb003043737403bff3175c082/internal/staging/checkpoint/options.go#L44)):*
> ```Go
> func (l limitLookahead) isOption() {}
> 
> type skipBackwardsDataCheck bool
> ```

`struct{}`, like the `disableStream` above.


<!-- Sent from Reviewable.io -->

2024-10-24 18:48 UTC, ryanluu12345 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1052)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @alicia-l2, @bobvawter, and @Jeremyyang920)

___
*[`internal/staging/checkpoint/options.go` line 44 at r4](https://reviewable.io/reviews/cockroachdb/replicator/1052#-O9zflL416-YO20cVBW0:-O9zqodh2NvZ7EEZH2-3:bvljs2b) ([raw file](https://github.com/cockroachdb/replicator/blob/4957f647e1290d2eb003043737403bff3175c082/internal/staging/checkpoint/options.go#L44)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

`struct{}`, like the `disableStream` above.
</blockquote></details>

Addressed!


<!-- Sent from Reviewable.io -->

2024-10-25 00:54 UTC, bobvawter approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/1052#-:-OA09iDC2ynFL6Ecl4qf:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @alicia-l2 and @Jeremyyang920)



<!-- Sent from Reviewable.io -->

2024-10-25 01:32 UTC, merged