schemawatch: Extract table dependency information from target
cockroachdb/replicator pull request #991
Opened 2024-09-03 21:06 UTC by bobvawter

Previously, the table-dependency queries asked the target database to return the referential level of tables in the target schema. This change updates the queries to return parent-child tuples and computes the table-level within Replicator. Having the extra data within Replicator also allows us to compute the strongly-connected FK components within the target schema. This will enable an upcoming change to BestEffort mode to allow it to operate over groups of connected tables, rather than on a per-table basis.

Summary of changes:
- The SchemaData and ColData types are moved into a new file, schema_data_test.go.
- A SchemaData now expresses a variety of relationships between connected tables. This necessitates an update to how a SchemaData is serialized, and has a few knock-on effects in the schema backup code.
- An unreferenced method, watcher.Snapshot() is deleted.
- The queries in dependencies.go are updated to return tuples of parent-to-child relationships. These values are processed by a new SchemaData.SetDependencies() method that populates the component-related fields.
- The aggregation behavior in orderedAcceptor is updated to iterate over tables in reverse-dependency order when encountering deletions.

2024-09-04 19:27 UTC, sravotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - just a couple of small comments.

> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/991#-:-O5yVLvN2eypcDG-QLGa:bqejz0n)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @bobvawter, @BramGruneir, @Jeremyyang920, and @MattWhelan)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5yCIJG4cOjciHw92qb):*
schema_data.go?
___
*[`internal/target/schemawatch/coldata.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5yEwJU8Ayc0jIJ38M6:-O5yEwJV31yOhsl3VxYa:byjabld) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/coldata.go#L248)):*
> ```Go
>      pk_cols  AS (SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME FROM ALL_CONSTRAINTS WHERE CONSTRAINT_TYPE='P'),
>      acc AS (SELECT OWNER, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, POSITION, 't' IS_PK FROM ALL_CONS_COLUMNS)
> SELECT /*+  gather_plan_statistics */
> ```

Could add a comment above to explain about this hint?


<!-- Sent from Reviewable.io -->

2024-09-04 19:44 UTC, BramGruneir requested changes
Looks good, just a few small questions.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/991#-:-O5yZ9fs46BKV6SZKKeH:b-b6yval)* status: all files reviewed, 8 unresolved discussions (waiting on @bobvawter, @Jeremyyang920, and @MattWhelan)

___
*[`internal/target/schemawatch/coldata.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5xKBar21m_3QI_ulxI:-O5xKBar21m_3QI_ulxJ:bijbaya) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/coldata.go#L248)):*
> ```Go
>      pk_cols  AS (SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME FROM ALL_CONSTRAINTS WHERE CONSTRAINT_TYPE='P'),
>      acc AS (SELECT OWNER, TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, POSITION, 't' IS_PK FROM ALL_CONS_COLUMNS)
> SELECT /*+  gather_plan_statistics */
> ```

Can you add a note about this in the comment above?  Just to it's not weird. 
___
*[`internal/target/schemawatch/dependencies.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5xYkG-9ntRqZ-uYUtI:-O5xYkG-9ntRqZ-uYUtJ:b-dxf79a) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/dependencies.go#L130)):*
> ```Go
>     FROM ALL_TABLES
>     WHERE OWNER = :owner)
> SELECT /*+  gather_plan_statistics */ * FROM seeds
> ```

please add a note about this in the comment above
___
*[`internal/target/schemawatch/dependencies.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5x_W6R-5cveYDe2Kf-:-O5x_W6R-5cveYDe2Kf0:bjhthao) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/dependencies.go#L204)):*
> ```Go
>                    (r.child_catalog, r.child_schema, r.child_table_name)
>    ),
>   tables
> ```

I think you accidentally dropped the comment for `tables`
___
*[`internal/target/schemawatch/dependencies.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5x_jae07a3sg9FQXsn:-O5x_jae07a3sg9FQXso:b-lcwtov) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/dependencies.go#L213)):*
> ```Go
>     AS (
>       SELECT
>         NULL, NULL, NULL,
> ```

I know it will be thrown away, but can you add names here to the nulls to make it a bit clearer?
___
*[`internal/types/acceptors.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5xk7Yg8Jleavkbh82B:-O5xk7Yg8Jleavkbh82C:b-rzrgu7) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/types/acceptors.go#L177)):*
> ```Go
> 
> 	// Final flush. In cases where there are no deletions, this should
> 	// be the only time a flush happens.
> ```

There can be no deletes left here?
___
*[`internal/types/schema_data.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5yMyFC-mUKYlsAk4cg:-O5yMyFC-mUKYlsAk4ch:b-eweq4y) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/types/schema_data.go#L62)):*
> ```Go
> 	// ReverseOrder is sorted such that child tables will appear before
> 	// parent tables.
> 	ReverseOrder []ident.Table `json:"-"`
> ```

Why do you need both of these?  Can't you just iterate backwards?


<!-- Sent from Reviewable.io -->

2024-09-05 13:15 UTC, bobvawter reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/991)* status: all files reviewed, 6 unresolved discussions (waiting on @BramGruneir, @Jeremyyang920, and @MattWhelan)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5yCIJG4cOjciHw92qb):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

schema_data.go?
</blockquote></details>

Done.
___
*[`internal/target/schemawatch/coldata.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5xKBar21m_3QI_ulxI:-O61GzaM3n1l5fZecfOG:bb6un1j) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/coldata.go#L248)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you add a note about this in the comment above?  Just to it's not weird.
</blockquote></details>

Done
___
*[`internal/target/schemawatch/coldata.go` line 248 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5yEwJU8Ayc0jIJ38M6:-O61GzvX1BLT6KPY5EC5:bb6un1j) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/coldata.go#L248)):*
<details><summary><i>Previously, sravotto (silvano) wrote…</i></summary><blockquote>

Could add a comment above to explain about this hint?
</blockquote></details>

Done
___
*[`internal/target/schemawatch/dependencies.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5xYkG-9ntRqZ-uYUtI:-O61H13p1PPl20EQ0wMa:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/dependencies.go#L130)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

please add a note about this in the comment above
</blockquote></details>

Done.
___
*[`internal/target/schemawatch/dependencies.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5x_W6R-5cveYDe2Kf-:-O61HRJ60nTe6xHlBWGZ:bxhupgd) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/dependencies.go#L204)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I think you accidentally dropped the comment for `tables`
</blockquote></details>

The `tables` clause was actually a leftover. I have removed it from the query.
___
*[`internal/target/schemawatch/dependencies.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5x_jae07a3sg9FQXsn:-O61HlK62MLatVBuJOJz:b-896fix) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/target/schemawatch/dependencies.go#L213)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I know it will be thrown away, but can you add names here to the nulls to make it a bit clearer?
</blockquote></details>

Done.
___
*[`internal/types/acceptors.go` line 177 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5xk7Yg8Jleavkbh82B:-O61ICLV7Kc9K7NWlccP:b-1w34t) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/types/acceptors.go#L177)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

There can be no deletes left here?
</blockquote></details>

Correct. I have updated the comment to reference the loop above.
___
*[`internal/types/schema_data.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/replicator/991#-O5yMyFC-mUKYlsAk4cg:-O61Igi_5BjaLG-aflu5:b-jmo9pi) ([raw file](https://github.com/cockroachdb/replicator/blob/e8a58089018ad6005fddfc554d700ed54dad4eef/internal/types/schema_data.go#L62)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why do you need both of these?  Can't you just iterate backwards?
</blockquote></details>

It makes the `orderedAdapter.flush()` code much cleaner (there's only one loop construct) to have a cached, reversed slice somewhere.  Since it's only populated by `SchemaData.SetDependencies()`, it seemed like a useful convenience.


<!-- Sent from Reviewable.io -->

2024-09-05 15:34 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/replicator/991#-:-O61okab1YhfU6PxBvUS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Jeremyyang920 and @MattWhelan)



<!-- Sent from Reviewable.io -->

2024-09-05 17:39 UTC, merged